### ISSUE TITLE
[Recherche] recherche par critères

### ISSUE THREAD

**Issue by TomGallon** [get-focus/focus4#13]
J'avais en tête d'adresser la recherche par critères, qui adresse un besoin complémentaire pour l'utilisateur, de cette manière :

![image](https://cloud.githubusercontent.com/assets/5349745/24698647/ba507eaa-19f1-11e7-90d3-7eada4deeb4f.png)

Coté FOCUS, la mise en place pourrait être faite par fichier de configuration.
Côté Backend, il y a peu de travail à mon sens, à part ouvrir un peu l'API (peut-être).

**Comment by JabX** [comment]
L'objet `criteria` du `QueryInput`, qui contient pour l'instant `query` et `scope` va devenir customisable pour pouvoir ajouter des critères supplémentaires.

Le store de recherche va contenir un objet `criteria` en plus qui contiendra les critères personnalisés, et l'objet envoyé au serveur sera `{query, scope, ...criteria}`. Vertigo est déjà capable de gérer des objets de critères personnalisés donc il n'y aura rien à prévoir de ce côté-là.

Il n'y aura pas de composant supplémentaire pour saisir les critères, chaque développeur construira le sien en fonction de ses besoins. Il sera possible par contre d'en passer à la SearchBar pour qu'elle l'affiche en dropdown.

Les critères seront optionnellement affichés sous format texte dans la zone de recherche (`critere:valeur`) et modifiable ainsi.

La phrase de résultat deviendra "X résultats pour "query" par "scope" "facet" "facet" "filtre" "filtre" groupé par "group".

A priori le sujet sera traité la semaine prochaine.
