### ISSUE TITLE
[Advanced search]  Empty state vs.  No results

### ISSUE THREAD

**Issue by pierbrisson** [get-focus/focus4#29]
In the advanced search, the empty state is displayed when a search returns no results

The following search/filter should display the fact that there are no results rather than an empty state saying that you can add objects

![image](https://user-images.githubusercontent.com/8983628/27801444-58b5dc30-601e-11e7-984d-1107c1ad4ef8.png)

**Comment by JabX** [comment]
La distinction est à faire dans le composant d'Empty State lui-même, il suffit de lire l'état du store de recherche pour en déduire ce qu'on veut y afficher.

C'est beaucoup plus flexible que de proposer plusieurs composants pour chaque usage.
